[package]
name = "voxel"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.18.0", default-features = false, features = ["bevy_render", "bevy_image", "bevy_camera", "bevy_window", "bevy_winit", "png", "bevy_pbr", "debug", "tonemapping_luts", "zstd_rust", "bevy_light", "bevy_post_process", "bevy_log", "bevy_picking", "x11", "sysinfo_plugin"] }
bevy-inspector-egui = "0.36.0"
bevy_flycam = "0.18.0"
noise = "0.9.0"
tinyvec = { version = "1.10.0", features = ["alloc"] }
fxhash = "0.2.1"

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

[profile.release]
lto = false
opt-level = 3
codegen-units = 1
incremental = true
debug = false
